package id.ac.poliban.mi.firda.listnegara;

import java.util.ArrayList;
import java.util.List;

public class CountryDAta {
    static List<Country> getAllContries() {
        List<Country> data = new ArrayList<>();
        {
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png","Argentina","Republik Argentina (bahasa Spanyol: República Argentina), lebih dikenal sebagai Argentina, merupakan negara Amerika Latin terbesar kedua dan negara berbahasa Spanyol terbesar di dunia. Argentina terletak di bagian selatan benua Amerika Selatan. Posisinya berada di antara Pegunungan Andes di barat dan Samudra Atlantik di selatan. Lokasi ini membuat Argentina dikenal sebagai 'negara paling selatan di selatan' (bahasa Spanyol: \"Sur del sur\"). Argentina mempunyai kawasan yang luas dan merupakan negara terbesar kedelapan di dunia sedangkan ibu kotanya Buenos Aires adalah salah satu metropolitan yang terpadat di dunia. Negara ini berbatasan dengan Paraguay dan Bolivia di sebelah utara, Brasil dan Uruguay di timur laut dan Chili di sebelah barat. Nama resminya untuk kepentingan legislatif ialah 'Negara Argentina' (Nacion Argentina)."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png","Brazil","Republik Federatif Brasil atau Republik Federal Brasil (bahasa Portugis: República Federativa do Brasil, bahasa Inggris: Federative Republic of Brazil, bahasa Latin: Respublica Foederativa Brasiliae) adalah negara paling besar dan paling banyak penduduknya(204.5 juta jiwa pada tahun 2017[4]) di Amerika Selatan. Negara ini merupakan negara paling timur di Benua Amerika dan berbatasan dengan Pegunungan Andes dan Samudra Atlantik. Nama Brasil diambil dari nama Kayu Brasil, sejenis kayu lokal. Brasil merupakan tempat pertanian ekstensif dan hutan hujan tropis. Sebagai bekas koloni Portugal, bahasa resmi Brasil adalah bahasa Portugis. Selain itu, Brasil juga sebagai penghasil kopi terbesar di dunia."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/125px-Flag_of_Indonesia.svg.png", "Indonesia", "Republik Indonesia (RI) atau Negara Kesatuan Republik Indonesia (NKRI), atau lebih umum disebut Indonesia, adalah negara di Asia Tenggara yang dilintasi garis khatulistiwa dan berada di antara daratan benua Asia dan Australia, serta antara Samudra Pasifik dan Samudra Hindia. Indonesia adalah negara kepulauan terbesar di dunia yang terdiri dari 17.504 pulau.[11] Nama alternatif yang biasa dipakai adalah Nusantara.[12] Dengan populasi Hampir 270.054.853 jiwa pada tahun 2018,[13] Indonesia adalah negara berpenduduk terbesar keempat di dunia dan negara yang berpenduduk Muslim terbesar di dunia, dengan lebih dari 230 juta jiwa.[14][15]\n" + "Bentuk negara Indonesia adalah negara kesatuan dan bentuk pemerintahan Indonesia adalah republik, dengan Dewan Perwakilan Rakyat, Dewan Perwakilan Daerah dan Presiden yang dipilih secara langsung."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png", "United Kingdom", "Belanda (bahasa Belanda: Nederland [ˈneːdərˌlɑnt]  ( dengarkan)) adalah sebuah negara peserta Kerajaan Belanda, yang terdiri dari dua belas provinsi di Eropa Barat Laut, dan tiga pulau di Karibia. Kata Belanda dalam bahasa Indonesia adalah pinjaman yang cacat dari kosakata Portugis: holanda, olanda, wolanda, bolanda, dan terakhir menjadi belanda. Belanda Eropa berbatasan dengan Laut Utara di utara, dan barat, Belgia di selatan, dan Jerman di timur, dan berbagi perbatasan bahari[11] dengan Belgia, Jerman, dan Britania Raya. Belanda menganut demokrasi parlementer yang disusun sebagai negara kesatuan. Ibu kotanya adalah Amsterdam, sedangkan pusat pemerintahan, dan kedudukan monarkinya berada di Den Haag.[12] Belanda sebagai keseluruhan seringkali disebut \"Holland\", meskipun Holland Utara, dan Selatan hanyalah dua dari dua belas provinsinya. Nama resmi saat ini adalah Kerajaan Belanda."));
            data.add(new Country("https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png", "Spain", "Spanyol (bahasa Spanyol: España [esˈpaɲa] ( simak)), secara resmi dikenal dengan sebutan Kerajaan Spanyol (bahasa Spanyol: Reino de España) adalah sebuah negara di Eropa barat daya yang, bersama Portugal, terdapat di Semenanjung Iberia. Batas darat Spanyol dengan Eropa adalah Pegunungan Pirenia dengan Prancis dan Andorra. Wilayahnya terdiri dari kota Ceuta dan Melilla di Afrika Utara, Kepulauan Canary di Samudra Atlantik, dan berbagai pulau di Laut Tengah."));
        }
        return data;
    }
}
